name: Fix KernelSU

on:
  workflow_dispatch:

jobs:
  fix-ksu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Remove KernelSU-Next
        run: |
          rm -rf KernelSU-Next
          rm -rf .git/modules/KernelSU-Next

      - name: Commit cleanup
        run: |
          git add .
          git commit -m "Remove KernelSU-Next (using ReSukiSU instead)"
          git push
