name: Cherry-pick SUSFS Commit

on:
  workflow_dispatch:

jobs:
  cherry-pick:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kernel
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Add source repo
        run: |
          git remote add susfs https://github.com/Siarrrrrrrr/VEUX-Positron-Resukisu-Susfs.git
          git fetch susfs

      - name: Cherry-pick commit
        run: |
          git cherry-pick 069ab8de1e4c6485c13fea3eafe2351ba98ce65d || true

      - name: Commit result
        run: |
          git add .
          git commit -m "Cherry-pick SUSFS integration commit" || echo "Nothing to commit"
          git push
